[build]
  command = "npm run build"

[functions]
  included_files = ["views/**", "public/**"]

[[redirects]]
  from = "/"
  to = "https://afterpose.com"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/microsite/:splat"
  status = 200