[build]
  command = "npm install && npm run build"
  functions = "functions"

[functions]
  included_files = ["views/**", "public/**"]

[[redirects]]
  from = "/"
  to = "https://poseapps.com"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200