[functions]
  node_bundler = "esbuild"
  included_files = ["views/**"]

[[redirects]]
  from = "/"
  to = "https://afterpose.com"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/microsite/:splat"
  status = 200